version: '3'

services:
  cloud_beaver:
    image: dbeaver/cloudbeaver:23.2.2
    ports:
      - 8978:8978
    volumes:
      - ./workspace:/opt/cloudbeaver/workspace
    restart: always

  db_server:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "Test_password3306"
      MYSQL_ROOT_PASSWORD: "Test_password3306"
      MYSQL_PORT: "3306"
    restart: always
    volumes:
      - mariadb-sample-volume:/var/lib/mysql
      - ./mysql/setup:/docker-entrypoint-initdb.d

volumes:
  mariadb-sample-volume:
